USE DATHANGONLINE
GO
--HỦY ĐƠN HÀNG - KHÁCH HÀNG
CREATE OR ALTER
PROC USP_HUY_DH
@MA_DH CHAR(8)
AS
BEGIN TRAN
	SELECT DH.MA_DH, DH.MA_KH, DH.PHI_TONG
	FROM TAI_KHOAN TK JOIN KHACH_HANG KH ON TK.MA_TK = KH.MA_TK 
			JOIN DON_HANG DH ON KH.MA_KH = DH.MA_KH
	WHERE TK.TEN_TK = 'tkkhachhang1'--CURRENT_USER -- ĐƠN HÀNG CỦA KHÁCH HÀNG

	SELECT PP.*
	FROM PHAN_PHOI PP

	WAITFOR DELAY '0:0:5'

	/*IF @MA_DH NOT IN (SELECT DH.MA_DH
						FROM TAI_KHOAN TK JOIN KHACH_HANG KH ON TK.MA_TK = KH.MA_TK 
								JOIN DON_HANG DH ON KH.MA_KH = DH.MA_KH
						WHERE TK.TEN_TK = CURRENT_USER)
	BEGIN 
		PRINT 'BẠN KHÔNG THỂ HỦY ĐƠN HÀNG ' + @MA_DH
		RETURN
	END*/

	DELETE FROM TRANG_THAI WHERE TRANG_THAI.MA_DH = @MA_DH

	DELETE FROM CHI_TIET_DH WHERE CHI_TIET_DH.MA_DH = @MA_DH

	DELETE FROM DON_HANG WHERE DON_HANG.MA_DH = @MA_DH

	DECLARE @MA_CN CHAR(8), @SOLUONG INT
	SELECT @MA_CN = (SELECT DH.MA_CN
						FROM DON_HANG DH
						WHERE DH.MA_DH = @MA_DH)
	SELECT @SOLUONG = (SELECT CT.SO_LUONG
						FROM CHI_TIET_DH CT
						WHERE CT.MA_DH = @MA_DH)
	UPDATE PHAN_PHOI
	SET PHAN_PHOI.SO_LUONG_TON_KHO += (SELECT CT.SO_LUONG
										FROM CHI_TIET_DH CT
										WHERE CT.MA_DH = @MA_DH)
	WHERE PHAN_PHOI.MA_CN = @MA_CN AND PHAN_PHOI.MA_SP = (SELECT CT.MA_SP
															FROM CHI_TIET_DH CT
															WHERE CT.MA_DH = @MA_DH)
	SELECT PP.*
	FROM PHAN_PHOI PP

COMMIT TRAN
GO

-- TÀI XẾ NHẬN ĐƠN HÀNG 
CREATE OR ALTER
PROC USP_NHAN_DH
@MA_DH CHAR(8)
AS
BEGIN TRAN
	BEGIN TRY
		DECLARE @MATX CHAR(8)
		SELECT @MATX = (SELECT TX.MA_TX
							FROM TAI_KHOAN TK JOIN TAI_XE TX ON TK.MA_TK = TX.MA_TK
							WHERE TK.TEN_TK = 'tktaixe1')-- CURRENT_USER)

		DECLARE @TEN_KV NVARCHAR(30)
		SELECT @TEN_KV = (SELECT KV.TEN_KV
							FROM TAI_KHOAN TK JOIN TAI_XE TX ON TK.MA_TK = TX.MA_TK 
									JOIN HOAT_DONG HD ON TX.MA_TX = HD.MA_TX 
									JOIN KHU_VUC_HOAT_DONG KV ON HD.MA_KV = KV.MA_KV
							WHERE TK.TEN_TK = 'tktaixe1')

		SELECT DH.MA_DH, DH.MA_TX, DH.PHI_TONG
		FROM DON_HANG DH
		WHERE DH.THANH_PHO LIKE + '%' + @TEN_KV + '%'

		WAITFOR DELAY '0:0:5'

		UPDATE DON_HANG
		SET DON_HANG.MA_TX = @MATX
		WHERE DON_HANG.MA_DH = @MA_DH

		SELECT DH.*
		FROM TAI_KHOAN TK JOIN TAI_XE TX ON TK.MA_TK = TX.MA_TK
				JOIN DON_HANG DH ON TX.MA_TX = DH.MA_TX
		WHERE TK.TEN_TK = 'tktaixe1'
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000);
		SELECT @ErrorMessage = ERROR_MESSAGE()
		RAISERROR(@ErrorMessage,16,1)
		ROLLBACK TRAN
	END CATCH

COMMIT TRAN