USE DATHANGONLINE
GO

--KHÁCH HÀNG XEM THÀNH TIỀN CỦA ĐƠN HÀNG
CREATE OR ALTER
PROC USP_KH_SELECT_THANHTIEN
@MA_DH CHAR(8)
AS
BEGIN TRAN
	BEGIN TRY
		IF @MA_DH NOT IN (SELECT DH.MA_DH
							FROM DON_HANG DH)
		BEGIN 
			PRINT  @MA_DH + N' KHÔNG CÓ TRONG HỆ THỐNG'
			ROLLBACK TRAN
			RETURN
		END

		SELECT CT.*
		FROM CHI_TIET_DH CT
		WHERE CT.MA_DH = @MA_DH

		WAITFOR DELAY '0:0:05'

		SELECT DH.MA_DH AS MA_DON_HANG, DH.PHI_SP AS THANH_TIEN
		FROM DON_HANG DH
		WHERE DH.MA_DH = @MA_DH

	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000);
		SELECT @ErrorMessage = ERROR_MESSAGE()
		RAISERROR(@ErrorMessage,16,1)
		ROLLBACK TRAN	
	END CATCH
COMMIT TRAN
GO

--ĐỐI TÁC CẬP NHẬT GIÁ TIỀN SẢN PHẨM
CREATE OR ALTER
PROC USP_DT_UPDATE_SP
@MA_SP CHAR(8), @MA_CN CHAR(8), @GTIEN_MOI MONEY
AS
BEGIN TRAN
	BEGIN TRY
		SELECT PP.*
		FROM PHAN_PHOI PP
		WHERE PP.MA_CN =@MA_CN AND PP.MA_SP = @MA_SP

		EXEC USP_UPDATE_PHAN_PHOI @MA_SP, @MA_CN, @GTIEN_MOI

		SELECT PP.*
		FROM PHAN_PHOI PP
		WHERE PP.MA_CN =@MA_CN AND PP.MA_SP = @MA_SP
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000);
		SELECT @ErrorMessage = ERROR_MESSAGE()
		RAISERROR(@ErrorMessage,16,1)
		ROLLBACK TRAN	
	END CATCH
COMMIT TRAN
GO