CREATE DATABASE X
GO

USE X
GO

CREATE TABLE DOI_TAC
(
	MA_DT CHAR(8) PRIMARY KEY,
	MA_TK CHAR(8),
	MA_LH CHAR(8),
	TEN_DT NVARCHAR(50) UNIQUE,
	NGUOI_DAI_DIEN NVARCHAR(50),
	THANH_PHO NVARCHAR(30),
	QUAN NVARCHAR(20),
	SO_CHI_NHANH INT CHECK (SO_CHI_NHANH >= 0),
	SO_LUONG_DON INT CHECK (SO_LUONG_DON >= 0)
)
GO

CREATE TABLE HOP_DONG
(
	MA_HD CHAR(8) PRIMARY KEY,
	MA_DT CHAR(8),
	MA_SO_THUE VARCHAR(10) UNIQUE,
	NGAY_KI DATE,
	NGAY_HET_HAN DATE,
	PHI_HOA_HONG DEC(3,2) CHECK (PHI_HOA_HONG BETWEEN 0 AND 1),
	SO_CHI_NHANH_DK INT CHECK (SO_CHI_NHANH_DK > 0),
)
GO

CREATE TABLE DANH_SACH_HD
(
	MA_HD CHAR(8),
	STT INT NOT NULL,
	NGAY_KI DATE,
	NGAY_HET_HAN DATE

	PRIMARY KEY (MA_HD, STT)
)
GO

CREATE TABLE CHI_NHANH
(
	MA_CN CHAR(8) PRIMARY KEY,
	MA_DT CHAR(8),
	THANH_PHO NVARCHAR(30),
	QUAN NVARCHAR(20),
	PHUONG NVARCHAR(20),
	DUONG NVARCHAR(30)
)
GO

CREATE TABLE PHAN_PHOI
(
	MA_CN CHAR(8) NOT NULL,
	MA_SP CHAR(8) NOT NULL,
	SO_LUONG_TON_KHO INT CHECK (SO_LUONG_TON_KHO >= 0),
	GIA MONEY

	PRIMARY KEY (MA_CN, MA_SP)
)
GO

CREATE TABLE SAN_PHAM
(
	MA_SP CHAR(8) NOT NULL,
	MA_LH CHAR(8),
	TEN_SP NVARCHAR(50),
	MO_TA_SP NTEXT

	PRIMARY KEY (MA_SP)
)
GO

CREATE TABLE LOAI_HANG_HOA
(
	MA_LH CHAR(8) PRIMARY KEY,
	TEN_LH NVARCHAR(20),
)
GO

CREATE TABLE DON_HANG
(
	MA_DH CHAR(8) PRIMARY KEY,
	MA_KH CHAR(8),	
	MA_DT CHAR(8),
	MA_TX CHAR(8),
	MA_CN CHAR(8),
	DIA_CHI_GH NVARCHAR(100),
	THANH_PHO NVARCHAR(30),
	PHI_SP MONEY CHECK (PHI_SP >= 0),
	PHI_GH MONEY CHECK (PHI_GH >= 0),
	PHI_GIAM MONEY CHECK (PHI_GIAM >= 0),
	PHI_TONG MONEY CHECK (PHI_TONG >= 0),
	TRANG_THAI NVARCHAR(30) CHECK (TRANG_THAI = N'Đã đặt hàng' OR TRANG_THAI = N'Đã xác nhận' OR TRANG_THAI = N'Đang giao hàng' OR TRANG_THAI = N'Đã giao hàng' OR TRANG_THAI = N'Đã hủy'),
	HINH_THUC_THANH_TOAN NVARCHAR(30) CHECK (HINH_THUC_THANH_TOAN =	N'Tiền mặt' OR HINH_THUC_THANH_TOAN = N'Thẻ tín dụng' OR HINH_THUC_THANH_TOAN = N'Thẻ ghi nợ' OR HINH_THUC_THANH_TOAN = N'Ngân hàng liên kết'),
)
GO

CREATE TABLE TRANG_THAI
(
	MA_DH CHAR(8) NOT NULL,
	TEN_TRANG_THAI NVARCHAR(30) NOT NULL CHECK (TEN_TRANG_THAI = N'Đã đặt hàng' OR TEN_TRANG_THAI = N'Đã xác nhận' OR TEN_TRANG_THAI = N'Đang giao hàng' OR TEN_TRANG_THAI = N'Đã giao hàng' OR TEN_TRANG_THAI = N'Đã hủy'),
	THOI_GIAN DATETIME

	PRIMARY KEY (MA_DH, TEN_TRANG_THAI)
)
GO

CREATE TABLE CHI_TIET_DH
(
	MA_DH CHAR(8) NOT NULL,
	MA_SP CHAR(8) NOT NULL,
	SO_LUONG INT CHECK (SO_LUONG >= 0),
	THANH_TIEN MONEY CHECK (THANH_TIEN >= 0),

	PRIMARY KEY (MA_DH, MA_SP)
)
GO

CREATE TABLE KHACH_HANG
(
	MA_KH CHAR(8) PRIMARY KEY,
	MA_TK CHAR(8),
	TEN_KH NVARCHAR(30)
)
GO

CREATE TABLE TAI_XE
(
	MA_TX CHAR(8) PRIMARY KEY,
	MA_TK CHAR(8),
	TEN_TX NVARCHAR(30),
	CMND VARCHAR(12) UNIQUE NOT NULL,
	BIEN_SO_XE VARCHAR(15) UNIQUE NOT NULL,
	STK VARCHAR(15) UNIQUE NOT NULL,
	PHI_THUE_CHAN MONEY CHECK (PHI_THUE_CHAN >= 0)
)
GO

CREATE TABLE KHU_VUC_HOAT_DONG
(
	MA_KV CHAR(8) PRIMARY KEY,
	TEN_KV NVARCHAR(20)
)
GO

CREATE TABLE HOAT_DONG
(
	MA_TX CHAR(8),
	MA_KV CHAR(8),

	PRIMARY KEY(MA_KV, MA_TX)
)
GO

CREATE TABLE TAI_KHOAN
(
	MA_TK CHAR(8) PRIMARY KEY,
	TEN_TK VARCHAR(20) UNIQUE NOT NULL,
	MAT_KHAU VARCHAR(20) NOT NULL,
	LOAI_TK NVARCHAR(20) CHECK (LOAI_TK = N'Đối tác' OR LOAI_TK = N'Khách hàng' OR LOAI_TK = N'Nhân viên' OR LOAI_TK = N'Tài xế' OR LOAI_TK = N'Admin'),
	EMAIL VARCHAR(30),
	SDT VARCHAR(15),
	THANH_PHO NVARCHAR(20),
	QUAN NVARCHAR(20),
	PHUONG NVARCHAR(20),
	DUONG NVARCHAR(30),
	TRANG_THAI_TK NVARCHAR(30) CHECK (TRANG_THAI_TK = N'Đã kích hoạt' OR TRANG_THAI_TK = N'Chưa kích hoạt' OR TRANG_THAI_TK = N'Đã khóa')
)
GO

ALTER TABLE dbo.DOI_TAC ADD FOREIGN KEY (MA_TK) REFERENCES dbo.TAI_KHOAN (MA_TK)
ALTER TABLE dbo.DOI_TAC ADD FOREIGN KEY (MA_LH) REFERENCES dbo.LOAI_HANG_HOA (MA_LH)

ALTER TABLE dbo.HOP_DONG ADD FOREIGN KEY (MA_DT) REFERENCES dbo.DOI_TAC (MA_DT)

ALTER TABLE dbo.DANH_SACH_HD ADD FOREIGN KEY (MA_HD) REFERENCES dbo.HOP_DONG (MA_HD)

ALTER TABLE dbo.CHI_NHANH ADD FOREIGN KEY (MA_DT) REFERENCES dbo.DOI_TAC (MA_DT)

ALTER TABLE dbo.PHAN_PHOI ADD FOREIGN KEY (MA_CN) REFERENCES dbo.CHI_NHANH (MA_CN)
ALTER TABLE dbo.PHAN_PHOI ADD FOREIGN KEY (MA_SP) REFERENCES dbo.SAN_PHAM (MA_SP)

ALTER TABLE dbo.SAN_PHAM ADD FOREIGN KEY (MA_LH) REFERENCES dbo.LOAI_HANG_HOA (MA_LH)

ALTER TABLE dbo.DON_HANG ADD FOREIGN KEY (MA_DT) REFERENCES dbo.DOI_TAC (MA_DT)
ALTER TABLE dbo.DON_HANG ADD FOREIGN KEY (MA_KH) REFERENCES dbo.KHACH_HANG (MA_KH)
ALTER TABLE dbo.DON_HANG ADD FOREIGN KEY (MA_TX) REFERENCES dbo.TAI_XE (MA_TX)
ALTER TABLE dbo.DON_HANG ADD FOREIGN KEY (MA_CN) REFERENCES dbo.CHI_NHANH (MA_CN)

ALTER TABLE dbo.TRANG_THAI ADD FOREIGN KEY (MA_DH) REFERENCES dbo.DON_HANG (MA_DH)

ALTER TABLE dbo.CHI_TIET_DH ADD FOREIGN KEY (MA_DH) REFERENCES dbo.DON_HANG (MA_DH)
ALTER TABLE dbo.CHI_TIET_DH ADD FOREIGN KEY (MA_SP) REFERENCES dbo.SAN_PHAM (MA_SP)

ALTER TABLE dbo.KHACH_HANG ADD FOREIGN KEY (MA_TK) REFERENCES dbo.TAI_KHOAN (MA_TK)

ALTER TABLE dbo.TAI_XE ADD FOREIGN KEY (MA_TK) REFERENCES dbo.TAI_KHOAN (MA_TK)

ALTER TABLE dbo.HOAT_DONG ADD FOREIGN KEY (MA_TX) REFERENCES dbo.TAI_XE (MA_TX)
ALTER TABLE dbo.HOAT_DONG ADD FOREIGN KEY (MA_KV) REFERENCES dbo.KHU_VUC_HOAT_DONG (MA_KV)

