USE Z
GO

-- CREATE LOGIN
EXEC sp_addlogin 'tkdoitac1', 'mkdoitac1'
EXEC sp_addlogin 'tkdoitac2', 'mkdoitac2'
EXEC sp_addlogin 'tkdoitac4', 'mkdoitac4'
EXEC sp_addlogin 'tkkhachhang1', 'mkkhachhang1'
EXEC sp_addlogin 'tkkhachhang2', 'mkkhachhang2'
EXEC sp_addlogin 'tktaixe3', 'mktaixe3'
EXEC sp_addlogin 'tktaixe5', 'mktaixe5'
EXEC sp_addlogin 'tktaixe1', 'mktaixe1'
EXEC sp_addlogin 'tknhanvien1', 'mknhanvien1'
EXEC sp_addlogin 'tknhanvien2', 'mknhanvien2'
EXEC sp_addlogin 'admin1', 'admin1'

-- CREATE USER
CREATE USER DOITAC_1 FOR LOGIN tkdoitac1
CREATE USER DOITAC_2 FOR LOGIN tkdoitac2
CREATE USER DOITAC_4 FOR LOGIN tkdoitac4
CREATE USER KHACHHANG_1 FOR LOGIN tkkhachhang1
CREATE USER KHACHHANG_2 FOR LOGIN tkkhachhang2
CREATE USER TAIXE_1 FOR LOGIN tktaixe1
CREATE USER TAIXE_3 FOR LOGIN tktaixe3
CREATE USER TAIXE_5 FOR LOGIN tktaixe5
CREATE USER NHANVIEN_1 FOR LOGIN tknhanvien1
CREATE USER NHANVIEN_2 FOR LOGIN tknhanvien2
CREATE USER ADMIN_1 FOR LOGIN admin1

-- CREATE ROLE
EXEC sp_addrole 'DOI_TAC'
EXEC sp_addrole 'KHACH_HANG'
EXEC sp_addrole 'TAI_XE'
EXEC sp_addrole 'NHAN_VIEN'
EXEC sp_addrole 'QUAN_LY'

-- ADD USER TO ROLE
EXEC sp_addrolemember 'DOI_TAC', 'DOITAC_1'
EXEC sp_addrolemember 'DOI_TAC', 'DOITAC_2'
EXEC sp_addrolemember 'DOI_TAC', 'DOITAC_4'
EXEC sp_addrolemember 'KHACH_HANG', 'KHACHHANG_1'
EXEC sp_addrolemember 'KHACH_HANG', 'KHACHHANG_2'
EXEC sp_addrolemember 'TAI_XE', 'TAIXE_1'
EXEC sp_addrolemember 'TAI_XE', 'TAIXE_3'
EXEC sp_addrolemember 'TAI_XE', 'TAIXE_5'
EXEC sp_addrolemember 'NHAN_VIEN', 'NHANVIEN_1'
EXEC sp_addrolemember 'NHAN_VIEN', 'NHANVIEN_2'

--GRANT AUTHORIZATION
--QUAN_TRI
EXEC sp_addsrvrolemember 'admin1', 'sysadmin'

--NHAN_VIEN
GO
CREATE VIEW CV_NHANVIEN
AS
	SELECT *
	FROM TAI_KHOAN TK WHERE TK.LOAI_TK = N'Đối tác' OR TK.LOAI_TK = N'Khách hàng' OR TK.LOAI_TK = N'Tài xế'
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON CV_NHANVIEN TO NHAN_VIEN
GRANT SELECT, INSERT ON HOP_DONG TO NHAN_VIEN
GRANT SELECT, INSERT ON DANH_SACH_HD TO NHAN_VIEN
GRANT SELECT ON DOI_TAC TO NHAN_VIEN
GRANT SELECT ON TAI_XE TO NHAN_VIEN
GRANT UPDATE ON HOP_DONG(NGAY_KI, NGAY_HET_HAN, PHI_HOA_HONG) TO NHAN_VIEN
GO

--DOI_TAC
----Quyền truy cập đến thông tin tài khoản:
CREATE VIEW CV_TTDOITAC
AS
	SELECT TEN_DT, NGUOI_DAI_DIEN, EMAIL, SDT, DT.THANH_PHO, DT.QUAN
	FROM TAI_KHOAN TK JOIN DOI_TAC DT ON TK.MA_TK = DT.MA_TK
	WHERE TK.TEN_TK = CURRENT_USER -- TÀI KHOẢN ĐĂNG NHẬP HIỆN TẠI
GO

GRANT SELECT ON DOI_TAC TO DOI_TAC
GRANT UPDATE ON CV_TTDOITAC TO DOI_TAC
GRANT EXEC ON USP_THEM_SOLUONG TO DOI_TAC
GO

----Quyền quản lý chi nhánh
CREATE VIEW CV_QUANLY_CN
AS
	SELECT CN.*
	FROM TAI_KHOAN TK JOIN DOI_TAC DT ON TK.MA_TK = DT.MA_TK
			JOIN CHI_NHANH CN ON DT.MA_DT = CN.MA_CN
	WHERE TK.TEN_TK = CURRENT_USER 
GO

GRANT SELECT ON CV_QUANLY_CN TO DOI_TAC
GRANT UPDATE ON CV_QUANLY_CN(THANH_PHO, QUAN, PHUONG, DUONG) TO DOI_TAC
GO
----Quyền quản lý sản phẩm
CREATE VIEW CV_QUANLY_SP
AS
	SELECT SP.*
	FROM TAI_KHOAN TK JOIN DOI_TAC DT ON TK.MA_TK = DT.MA_TK
			JOIN CHI_NHANH CN ON DT.MA_DT = CN.MA_DT 
			JOIN PHAN_PHOI PP ON CN.MA_CN = PP.MA_CN
			JOIN SAN_PHAM SP ON PP.MA_CN = SP.MA_SP
	WHERE TK.TEN_TK = CURRENT_USER -- TÀI KHOẢN ĐĂNG NHẬP HIỆN TẠI
GO

GRANT SELECT ON CV_QUANLY_SP TO DOI_TAC
GRANT UPDATE ON CV_QUANLY_SP(TEN_SP, MO_TA) TO DOI_TAC
GRANT SELECT ON DON_HANG TO DOI_TAC
GRANT EXEC ON USP_INSERT_SP TO DOI_TAC
GRANT EXEC ON USP_UPDATE_PHAN_PHOI TO DOI_TAC
GRANT EXEC ON USP_UPDATE_CHI_TIET_DON_HANG TO DOI_TAC
GRANT EXEC ON USP_TAO_DH TO DOI_TAC
GO

----Quyền quản lý đơn hàng
CREATE VIEW CV_QUANLY_DH
AS
	SELECT DH.*
	FROM TAI_KHOAN TK JOIN DOI_TAC DT ON TK.MA_TK = DT.MA_TK
			JOIN DON_HANG DH ON DT.MA_DT = DH.MA_DT
	WHERE TK.TEN_TK = CURRENT_USER -- TÀI KHOẢN ĐĂNG NHẬP HIỆN TẠI
GO

GRANT SELECT ON CV_QUANLY_DH TO DOI_TAC
GO
	

--TAI_XE
CREATE VIEW CV_TAIXE
AS
	SELECT TEN_TX, CMND, BIEN_SO_XE, STK, PHI_THUE_CHAN, EMAIL, SDT, THANH_PHO, QUAN, PHUONG, DUONG
	FROM TAI_KHOAN TK JOIN TAI_XE TX ON TK.MA_TK = TX.MA_TK
	WHERE TK.TEN_TK = CURRENT_USER -- TÀI KHOẢN ĐĂNG NHẬP HIỆN TẠI
GO

GRANT SELECT, UPDATE ON CV_TAIXE TO TAI_XE
GO

----danh sách đơn hàng chưa nhận trong khu vực tài xế
CREATE VIEW CV_DANH_SACH_DON_HANG
AS
	SELECT DH.*
	FROM TAI_KHOAN TK JOIN TAI_XE TX ON TK.MA_TK = TX.MA_TK
			JOIN HOAT_DONG HD ON TX.MA_TX = HD.MA_TX
			JOIN KHU_VUC_HOAT_DONG KV ON HD.MA_KV = KV.MA_KV
			JOIN DON_HANG DH ON KV.TEN_KV = DH.THANH_PHO
	WHERE DH.MA_TX = NULL AND TK.TEN_TK = CURRENT_USER -- TÀI KHOẢN ĐĂNG NHẬP HIỆN TẠI
GO
GRANT SELECT ON CV_DANH_SACH_DON_HANG TO TAI_XE
GRANT UPDATE ON CV_DANH_SACH_DON_HANG(MA_TX) TO TAI_XE
GO

----Nhận và xử lý đơn hàng:
CREATE VIEW CV_TAIXE_DONHANG
AS
	SELECT TT.*
	FROM TAI_KHOAN TK JOIN TAI_XE TX ON TK.MA_TK = TX.MA_TK
			JOIN DON_HANG DH ON TX.MA_TX = DH.MA_TX
			JOIN TRANG_THAI TT ON DH.MA_DH = TT.MA_DH
	WHERE TK.TEN_TK = CURRENT_USER -- TÀI KHOẢN ĐĂNG NHẬP HIỆN TẠI
GO
GRANT INSERT ON TRANG_THAI TO TAI_XE
GRANT EXEC ON USP_NHAN_DH TO TAI_XE
GO

--KHACH_HANG
CREATE VIEW CV_KHACHHANG
AS
	SELECT KH.TEN_KH, TK.EMAIL, TK.SDT, TK.THANH_PHO, TK.QUAN, TK.PHUONG, TK.DUONG
	FROM TAI_KHOAN TK JOIN KHACH_HANG KH ON TK.MA_TK = KH.MA_TK
	WHERE TK.TEN_TK = CURRENT_USER -- TÀI KHOẢN ĐĂNG NHẬP HIỆN TẠI
GO

CREATE VIEW CV_KH_XEM_DH
AS
	SELECT DH.MA_DH, DH.PHI_GH, DH.PHI_GIAM, DH.PHI_SP, DH.PHI_TONG, DH.DIA_CHI_GH, DH.THANH_PHO, DH.TRANG_THAI
	FROM TAI_KHOAN TK JOIN KHACH_HANG KH ON TK.MA_TK = KH.MA_TK
			JOIN DON_HANG DH ON KH.MA_KH = DH.MA_KH
	WHERE TK.TEN_TK = CURRENT_USER
GO

GRANT SELECT, UPDATE ON CV_KHACHHANG TO KHACH_HANG
GRANT EXEC ON USP_XEM_SP_TEN TO KHACH_HANG
GRANT EXEC ON USP_XEM_SP_DM TO KHACH_HANG
GRANT EXEC ON USP_THEM_CHI_TIET_DH TO KHACH_HANG
GRANT SELECT ON CV_KH_XEM_DH TO KHACH_HANG
GRANT EXEC ON USP_HUY_DH TO KHACH_HANG
GO