-- Procedure --
USE DATHANGONLINE
GO

-- KHÁCH HÀNG TẠO ĐƠN HÀNG
CREATE OR ALTER
PROC USP_KH_TAO_DH
@MA_DH CHAR(8), @THANH_PHO NVARCHAR(30)
AS 
BEGIN
	DECLARE @MA_KH CHAR(8)
	SELECT @MA_KH = (SELECT	KH.MA_KH
						FROM TAI_KHOAN TK JOIN KHACH_HANG KH ON TK.MA_TK = KH.MA_TK
						WHERE TK.TEN_TK = CURRENT_USER)
	INSERT DON_HANG(MA_DH, MA_KH, MA_TX, MA_CN, 
					MA_DT, THANH_PHO, DIA_CHI_GH, PHI_SP, PHI_GIAM, PHI_GH, PHI_TONG, TRANG_THAI, HINH_THUC_THANH_TOAN)
	VALUES (@MA_DH, @MA_KH, NULL, NULL, NULL, @THANH_PHO, NULL, 0, 0, 0, 0, NULL, NULL)
END
GO

--THÊM SỐ LƯỢNG VÀO SỐ LƯỢNG TỒN KHO
CREATE OR ALTER
PROC USP_THEM_SOLUONG
@MA_CN CHAR(8), @MA_SP CHAR(8), @SLUONG INT
AS
BEGIN
	IF @MA_CN NOT IN (SELECT CN.MA_CN
						FROM CHI_NHANH CN)
	BEGIN
		PRINT @MA_CN + N' KHÔNG TỒN TẠI'
		RETURN
	END
	IF @MA_SP NOT IN (SELECT PP.MA_SP
						FROM PHAN_PHOI PP
						WHERE PP.MA_CN = @MA_CN)
	BEGIN
		PRINT @MA_CN + N' KHÔNG PHÂN PHỐI SẢN PHẨM CÓ MÃ ' + @MA_SP
		RETURN
	END

	UPDATE PHAN_PHOI
	SET PHAN_PHOI.SO_LUONG_TON_KHO = @SLUONG
	WHERE PHAN_PHOI.MA_CN = @MA_CN AND PHAN_PHOI.MA_SP = @MA_SP
END
GO

--Thêm CHI_TIET_DON_HANG--
CREATE OR ALTER
PROC USP_THEM_CHI_TIET_DH
@MA_DH CHAR(8), @MA_CN CHAR(8), @MA_SP CHAR(8), @SLUONG INT
AS
BEGIN
	IF @MA_SP NOT IN (SELECT PP.MA_SP
						FROM PHAN_PHOI PP
						WHERE PP.MA_CN = @MA_CN)
	BEGIN
		PRINT @MA_SP + N' KHÔNG CÓ TRONG ' + @MA_CN
		PRINT N'BẠN CẦN TẠO 1 ĐƠN HÀNG MỚI'
		RETURN
	END --chi nhánh A không phân phối sản phẩm X --> tạo đơn mới

	DECLARE @THANH_TIEN MONEY
	SELECT @THANH_TIEN = (SELECT PP.GIA * @SLUONG
							FROM PHAN_PHOI PP JOIN DON_HANG DH ON PP.MA_CN = DH.MA_CN
							WHERE PP.MA_SP = @MA_SP AND DH.MA_DH = @MA_DH)
	INSERT CHI_TIET_DH(MA_DH, MA_SP, SO_LUONG, THANH_TIEN) VALUES (@MA_DH, @MA_SP, @SLUONG, @THANH_TIEN)
	UPDATE DON_HANG 
	SET DON_HANG.PHI_SP += @THANH_TIEN, DON_HANG.PHI_TONG = DON_HANG.PHI_SP + DON_HANG.PHI_GH - PHI_GIAM
	WHERE DON_HANG.MA_DH = @MA_DH

	UPDATE PHAN_PHOI
	SET PHAN_PHOI.SO_LUONG_TON_KHO -= @SLUONG
	WHERE PHAN_PHOI.MA_CN = @MA_CN AND PHAN_PHOI.MA_SP = @MA_SP

END
GO

--TÍNH THÀNH TIỀN SẢN PHẨM VÀ TỔNG TIỀN
CREATE OR ALTER
PROC USP_THANHTIEN_TONGTIEN
@MA_DH CHAR(8)
AS
BEGIN
	IF @MA_DH NOT IN (SELECT CT.MA_DH
						FROM CHI_TIET_DH CT)
	BEGIN
		PRINT @MA_DH + N'KHÔNG TỒN TẠI'
		RETURN
	END

	DECLARE @THANH_TIEN MONEY
	SELECT @THANH_TIEN = (SELECT SUM(CT.THANH_TIEN)
							FROM CHI_TIET_DH CT
							WHERE CT.MA_DH = @MA_DH)

	DECLARE @TONG_TIEN MONEY
	UPDATE DON_HANG
	SET DON_HANG.PHI_SP = @THANH_TIEN, DON_HANG.PHI_TONG = @THANH_TIEN - DON_HANG.PHI_GIAM + DON_HANG.PHI_GH
	WHERE DON_HANG.MA_DH = @MA_DH
END
GO

--XEM DANH SÁCH SẢN PHẨM THEO TÊN
CREATE OR ALTER
PROC USP_XEM_SP_TEN
@TEN_SP NVARCHAR(50)
AS
BEGIN
	SELECT *
	FROM SAN_PHAM SP
	WHERE SP.TEN_SP LIKE '%' + @TEN_SP + '%'
END
GO

--XEM DANH SÁCH SẢN PHẨM THEO DANH MỤC
CREATE OR ALTER
PROC USP_XEM_SP_DM
@TEN_LH NVARCHAR(20)
AS
BEGIN
	SELECT SP.*
	FROM LOAI_HANG_HOA LH JOIN SAN_PHAM SP ON LH.MA_LH = SP.MA_LH
	WHERE LH.TEN_LH LIKE '%' + @TEN_LH + '%'
END
GO

--DROP PROC USP_THEM_CHI_TIET_DH

--CẬP NHẬT SỐ LƯỢNG SẢN PHẨM TRONG CHI TIẾT ĐƠN HÀNG
CREATE OR ALTER
PROC USP_UPDATE_CHI_TIET_DON_HANG
@MA_SP CHAR(8), @MA_DH CHAR(8), @SlUONG INT
AS
BEGIN
	DECLARE @SLUONG_C INT, @THANH_TIEN_C MONEY
	DECLARE @THANH_TIEN_M MONEY

	SELECT @SLUONG_C = (SELECT CT.SO_LUONG
						FROM CHI_TIET_DH CT
						WHERE CT.MA_DH = @MA_DH AND CT.MA_SP = @MA_SP )

	SELECT @THANH_TIEN_C = (SELECT CT.THANH_TIEN
							FROM CHI_TIET_DH CT
							WHERE CT.MA_DH = @MA_DH AND CT.MA_SP = @MA_SP )

	SELECT @THANH_TIEN_M = (SELECT PP.GIA * @SLUONG
							FROM PHAN_PHOI PP JOIN DON_HANG DH ON PP.MA_CN = DH.MA_CN
							WHERE PP.MA_SP = @MA_SP AND DH.MA_DH = @MA_DH)
	UPDATE CHI_TIET_DH
	SET CHI_TIET_DH.SO_LUONG = @SlUONG, CHI_TIET_DH.THANH_TIEN = @THANH_TIEN_M
	WHERE CHI_TIET_DH.MA_DH = @MA_DH AND CHI_TIET_DH.MA_SP = @MA_SP

	UPDATE DON_HANG
	SET DON_HANG.PHI_SP = DON_HANG.PHI_SP - @THANH_TIEN_C + @THANH_TIEN_M, 
		DON_HANG.PHI_TONG = DON_HANG.PHI_SP + DON_HANG.PHI_GH - PHI_GIAM
	WHERE DON_HANG.MA_DH = @MA_DH
	
END
GO

--CẬP NHẬT GIÁ TIỀN SẢN PHẨM
CREATE OR ALTER
PROC USP_UPDATE_PHAN_PHOI
@MA_SP CHAR(8), @MA_CN CHAR(8), @GTIEN_MOI MONEY
AS
BEGIN TRAN
	/*IF @MA_CN NOT IN (SELECT CN.MA_CN
						FROM TAI_KHOAN TK JOIN DOI_TAC DT ON TK.MA_TK = DT.MA_TK
								JOIN CHI_NHANH CN ON DT.MA_DT = CN.MA_DT
						WHERE TK.TEN_TK = CURRENT_USER)
	BEGIN
		PRINT @MA_CN + N' KHÔNG CÓ TRONG HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END*/

	IF @MA_SP NOT IN (SELECT PP.MA_SP
						FROM PHAN_PHOI PP
						WHERE PP.MA_CN = @MA_CN)
	BEGIN
		PRINT @MA_SP + N' KHÔNG CÓ TRONG HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END

	IF (@GTIEN_MOI <= 0)
	BEGIN
		PRINT N'GIÁ TIỀN CỦA SẢN PHẨM PHẢI KHÁC 0'
		RETURN
	END

	DECLARE @TIEN_CU MONEY
	SELECT @TIEN_CU = (SELECT PP.GIA
						FROM PHAN_PHOI PP
						WHERE PP.MA_CN = @MA_CN AND PP.MA_SP = @MA_SP)

	UPDATE PHAN_PHOI
	SET PHAN_PHOI.GIA = @GTIEN_MOI
	WHERE PHAN_PHOI.MA_CN = @MA_CN AND PHAN_PHOI.MA_SP = @MA_SP

	---CẬP NHẬT BẢNG CHI TIẾT ĐƠN HÀNG VÀ ĐƠN HÀNG

COMMIT TRAN
GO

--THÊM SẢN PHẨM
CREATE OR ALTER
PROC USP_INSERT_SP
@MA_SP CHAR(8), @MA_LH CHAR(8), @TEN_SP NVARCHAR(50), @MO_TA NTEXT, @MA_CN CHAR(8), @SlUONG INT, @GIA MONEY
AS
BEGIN TRAN
	IF @TEN_SP IN (SELECT SP.TEN_SP
					FROM SAN_PHAM SP)
	BEGIN
		PRINT @TEN_SP + N' đã tồn tại'
		RETURN
	END
	INSERT SAN_PHAM(MA_SP, MA_LH, TEN_SP, MO_TA_SP) VALUES (@MA_SP, @MA_LH, @TEN_SP, @MO_TA)
	
	IF @MA_CN NOT IN (SELECT CN.MA_CN
						FROM TAI_KHOAN TK JOIN DOI_TAC DT ON TK.MA_TK = DT.MA_TK
								JOIN CHI_NHANH CN ON DT.MA_DT = CN.MA_DT
						WHERE TK.TEN_TK = CURRENT_USER)
	BEGIN
		PRINT @MA_CN + N' không tồn tại'
		RETURN
	END
	INSERT PHAN_PHOI(MA_CN, MA_SP, SO_LUONG_TON_KHO, GIA) VALUES (@MA_CN, @MA_SP, @SlUONG, @GIA)
COMMIT TRAN
GO

