USE Z
GO

--CẬP NHẬT TÊN SẢN PHẨM
CREATE OR ALTER
PROC USP_UPDATE_TEN_SP
@TEN_SP_CU NVARCHAR(50), @TEN_SP_MOI NVARCHAR(50)
AS
BEGIN TRAN
	BEGIN TRY
		IF @TEN_SP_CU NOT IN (SELECT PP.TEN_SP
								FROM SAN_PHAM PP)
		BEGIN 
			PRINT @TEN_SP_CU + N' KHÔNG CÓ TRONG DANH SÁCH SẢN PHẨM'
			RETURN
		END

		UPDATE SAN_PHAM
		SET SAN_PHAM.TEN_SP = @TEN_SP_MOI
		WHERE SAN_PHAM.TEN_SP = @TEN_SP_CU

		WAITFOR DELAY '0:0:5'

		IF ((SELECT COUNT(*)
			FROM SAN_PHAM SP
			WHERE SP.TEN_SP = @TEN_SP_MOI) > 1)
		BEGIN 
			PRINT N'Tên sản phẩm trùng với tên sản phẩm có trong danh sách'
			ROLLBACK TRAN
		END
	END TRY
	BEGIN CATCH
		PRINT N'Lỗi hệ thống ' + ERROR_MESSAGE()		ROLLBACK TRAN
	END CATCH
COMMIT TRAN
GO

--XEM SẢN PHẨM THEO TÊN:
CREATE OR ALTER
PROC USP_SEARCH_SP
@TEN_SP NVARCHAR(50)
AS
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
	BEGIN TRY
		SELECT SP.*
		FROM SAN_PHAM SP
		WHERE SP.TEN_SP = @TEN_SP
	END TRY
	BEGIN CATCH
		PRINT N'Lỗi hệ thống ' + ERROR_MESSAGE()		ROLLBACK TRAN
	END CATCH
COMMIT TRAN