USE DATHANGONLINE
GO

--CẬP NHẬT TÊN SẢN PHẨM
CREATE OR ALTER
PROC USP_UPDATE_TEN_SP_FIX
@TEN_SP_CU NVARCHAR(50), @TEN_SP_MOI NVARCHAR(50)
AS
BEGIN TRAN
	BEGIN TRY
		UPDATE SAN_PHAM
		SET SAN_PHAM.TEN_SP = @TEN_SP_MOI
		WHERE SAN_PHAM.TEN_SP = @TEN_SP_CU

		WAITFOR DELAY '0:0:10'

		IF (@TEN_SP_MOI IN (SELECT SP.TEN_SP
								FROM SAN_PHAM SP))
		BEGIN 
			PRINT N'Tên sản phẩm trùng với tên sản phẩm có trong danh sách'
			ROLLBACK TRAN
		END
	END TRY
	BEGIN CATCH
		PRINT N'Lỗi hệ thống ' + ERROR_MESSAGE()		ROLLBACK TRAN
	END CATCH
COMMIT TRAN
GO

--XEM SẢN PHẨM THEO TÊN:
CREATE OR ALTER
PROC USP_SEARCH_SP_FIX
@TEN_SP NVARCHAR(50)
AS
BEGIN TRAN
	BEGIN TRY
		SELECT SP.*
		FROM SAN_PHAM SP
		WHERE SP.TEN_SP = @TEN_SP
	END TRY
	BEGIN CATCH
		PRINT N'Lỗi hệ thống ' + ERROR_MESSAGE()		ROLLBACK TRAN
	END CATCH
COMMIT TRAN