USE DATHANGONLINE
GO

--ĐỐI TÁC CẬP NHẬT GIÁ TIỀN SẢN PHẨM
CREATE OR ALTER
PROC USP_UPDATE_GIA_SP
@MA_SP CHAR(8), @MA_CN CHAR(8), @GTIEN_MOI MONEY
AS
BEGIN TRAN
	BEGIN TRY
		IF @MA_SP NOT IN (SELECT SP.MA_SP
							FROM SAN_PHAM SP)
		BEGIN
			PRINT @MA_SP + N' KHÔNG CÓ TRONG HỆ THỐNG'
			RETURN
		END

		IF @MA_CN NOT IN (SELECT CN.MA_CN
							FROM CHI_NHANH CN)
		BEGIN
			PRINT @MA_CN + N' KHÔNG CÓ TRONG HỆ THỐNG'
			RETURN
		END

		UPDATE PHAN_PHOI
		SET PHAN_PHOI.GIA = @GTIEN_MOI
		WHERE PHAN_PHOI.MA_CN = @MA_CN AND PHAN_PHOI.MA_SP = @MA_SP

		WAITFOR DELAY '0:0:5'		
		IF (@GTIEN_MOI <= 0)
		BEGIN
			PRINT N'GIÁ TIỀN CỦA SẢN PHẨM PHẢI KHÁC 0'
			ROLLBACK TRAN
		END

		SELECT PP.*
		FROM PHAN_PHOI PP
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000);
		SELECT @ErrorMessage = ERROR_MESSAGE()
		RAISERROR(@ErrorMessage,16,1)
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN
GO

--CHỌN MUA SẢN PHẨM - THÊM VÀO CHI TIẾT ĐƠN HÀNG
CREATE OR ALTER
PROC USP_MUA_SP
@MA_DH CHAR(8), @MA_CN CHAR(8), @MA_SP CHAR(8), @SLUONG INT
AS
BEGIN TRAN
	BEGIN TRY
		EXEC USP_THEM_CHI_TIET_DH @MA_DH, @MA_CN, @MA_SP, @SLUONG
		SELECT *
		FROM CHI_TIET_DH CT
		WHERE CT.MA_DH = @MA_DH
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000);
		SELECT @ErrorMessage = ERROR_MESSAGE()
		RAISERROR(@ErrorMessage,16,1)
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN
RETURN 0
GO