CREATE DATABASE COVID
GO

USE COVID
GO

CREATE TABLE DOI_TAC
(
	MA_DT NVARCHAR(10) PRIMARY KEY,
	MA_TK NVARCHAR(15),
	MA_HH NVARCHAR(10),
	TEN_DT NVARCHAR(50) UNIQUE NOT NULL,
	NGUOI_DAI_DIEN NVARCHAR(50),
	THANH_PHO NVARCHAR(20),
	QUAN INT,
	SO_CHI_NHANH INT CHECK (SO_CHI_NHANH >= 0),
	SO_LUONG_DON INT CHECK (SO_LUONG_DON >= 0)
)
GO

CREATE TABLE HOP_DONG
(
	MA_HD NVARCHAR(10) PRIMARY KEY,
	MA_DT NVARCHAR(10),
	MA_SO_THUE NVARCHAR(10) UNIQUE NOT NULL,
	NGAY_KI DATE,
	NGAY_HET_HAN DATE,
	PHI_HOA_HONG INT CHECK (PHI_HOA_HONG >= 0),
	SO_CHI_NHANH_DK INT CHECK (SO_CHI_NHANH_DK > 0),
)
GO

CREATE TABLE DANH_SACH_HD
(
	MA_HD NVARCHAR(10) NOT NULL,
	STT INT NOT NULL,
	NGAY_KI DATE,
	NGAY_HET_HAN DATE

	PRIMARY KEY (MA_HD, STT)
)
GO

CREATE TABLE CHI_NHANH
(
	MA_CN NVARCHAR(10) PRIMARY KEY,
	MA_DT NVARCHAR(10),
	THANH_PHO NVARCHAR(20),
	QUAN INT,
	PHUONG INT,
	DUONG NVARCHAR(20)
)
GO

CREATE TABLE PHAN_PHOI
(
	MA_CN NVARCHAR(10) NOT NULL,
	MA_SP NVARCHAR(10) NOT NULL,
	SO_LUONG_TON_KHO INT CHECK (SO_LUONG_TON_KHO >= 0),
	GIA INT

	PRIMARY KEY (MA_CN, MA_SP)
)
GO

CREATE TABLE SAN_PHAM
(
	MA_SP NVARCHAR(10) NOT NULL,
	MA_CN NVARCHAR(10) NOT NULL,
	MA_HH NVARCHAR(10),
	TEN_SP NVARCHAR(50),
	MO_TA_SP NVARCHAR(100)

	PRIMARY KEY (MA_CN, MA_SP)
)
GO

CREATE TABLE HANG_HOA
(
	MA_HH NVARCHAR(10) PRIMARY KEY,
	TEN_HH NVARCHAR(20),
)
GO

CREATE TABLE DON_HANG
(
	MA_DH NVARCHAR(10) PRIMARY KEY,
	DIA_CHI_GH NVARCHAR(20),
	PHI_SP INT CHECK (PHI_SP >= 0),
	PHI_GH INT CHECK (PHI_GH >= 0),
	PHI_GIAM INT CHECK (PHI_GIAM >= 0),
	PHI_TONG INT CHECK (PHI_TONG >= 0),
	TRANG_THAI NVARCHAR(10) CHECK (TRANG_THAI = N'Đã đặt hàng' OR TRANG_THAI = N'Đã xác nhận' OR TRANG_THAI = N'Đang giao hàng' OR TRANG_THAI = N'Đã giao hàng' OR TRANG_THAI = N'Đã hủy'),
	HINH_THUC_THANH_TOAN NVARCHAR(10) CHECK (HINH_THUC_THANH_TOAN =	N'Tiền mặt' OR HINH_THUC_THANH_TOAN = N'Thẻ tín dụng' OR HINH_THUC_THANH_TOAN = N'Thẻ ghi nợ' OR HINH_THUC_THANH_TOAN = N'Ngân hàng liên kết')
)
GO

CREATE TABLE TRANG_THAI
(
	MA_DH NVARCHAR(10) NOT NULL,
	TEN_TRANG_THAI NVARCHAR(10) NOT NULL CHECK (TEN_TRANG_THAI = N'Đã đặt hàng' OR TEN_TRANG_THAI = N'Đã xác nhận' OR TEN_TRANG_THAI = N'Đang giao hàng' OR TEN_TRANG_THAI = N'Đã giao hàng' OR TEN_TRANG_THAI = N'Đã hủy'),
	THOI_GIAN TIME

	PRIMARY KEY (MA_DH, TEN_TRANG_THAI)
)
GO

CREATE TABLE CHI_TIET_DH
(
	MA_DH NVARCHAR(10) NOT NULL,
	MA_SP NVARCHAR(10) NOT NULL,
	SO_LUONG INT CHECK (SO_LUONG >= 0),
	THANH_TIEN INT CHECK (THANH_TIEN >= 0),

	PRIMARY KEY (MA_DH, MA_SP)
)
GO

CREATE TABLE KHACH_HANG
(
	MA_KH NVARCHAR(10) PRIMARY KEY,
	MA_TK NVARCHAR(15),
	TEN_KH NVARCHAR(20)
)
GO

CREATE TABLE TAI_XE
(
	MA_TX NVARCHAR(10) PRIMARY KEY,
	MA_TK NVARCHAR(15),
	MA_KV NVARCHAR(10),
	TEN_TX NVARCHAR(20),
	CMND NVARCHAR(15) UNIQUE NOT NULL,
	BIEN_SO_XE NVARCHAR(15) UNIQUE NOT NULL,
	STK NVARCHAR(15) UNIQUE NOT NULL,
	PHI_THUE_CHAN INT CHECK (PHI_THUE_CHAN >= 0)
)
GO

CREATE TABLE KHU_VUC_HOAT_DONG
(
	MA_KV NVARCHAR(10) PRIMARY KEY,
	TEN_KV NVARCHAR(20)
)
GO

CREATE TABLE TAI_KHOAN
(
	MA_TK NVARCHAR(15) PRIMARY KEY,
	TEN_TK NVARCHAR(20) UNIQUE NOT NULL,
	LOAI_TK NVARCHAR(20) CHECK (LOAI_TK = 'Đối tác' OR LOAI_TK = 'Khách hàng' OR LOAI_TK = 'Nhân viên' OR LOAI_TK = 'Tài xế' OR LOAI_TK = 'Admin'),
	MAT_KHAU NVARCHAR(20),
	EMAIL NVARCHAR(30),
	SDT VARCHAR(15),
	THANH_PHO NVARCHAR(20),
	QUAN INT,
	PHUONG INT,
	DUONG NVARCHAR(15)
)
GO

ALTER TABLE dbo.DOI_TAC ADD FOREIGN KEY (MA_TK) REFERENCES dbo.TAI_KHOAN (MA_TK)
ALTER TABLE dbo.DOI_TAC ADD FOREIGN KEY (MA_HH) REFERENCES dbo.HANG_HOA (MA_HH)
ALTER TABLE dbo.HOP_DONG ADD FOREIGN KEY (MA_DT) REFERENCES dbo.DOI_TAC (MA_DT)
ALTER TABLE dbo.DANH_SACH_HD ADD FOREIGN KEY (MA_HD) REFERENCES dbo.HOP_DONG (MA_HD)
ALTER TABLE dbo.CHI_NHANH ADD FOREIGN KEY (MA_DT) REFERENCES dbo.DOI_TAC (MA_DT)
ALTER TABLE dbo.PHAN_PHOI ADD FOREIGN KEY (MA_CN) REFERENCES dbo.CHI_NHANH (MA_CN)
ALTER TABLE dbo.PHAN_PHOI ADD FOREIGN KEY (MA_SP) REFERENCES dbo.SAN_PHAM (MA_SP) -- lỗi
ALTER TABLE dbo.SAN_PHAM ADD FOREIGN KEY (MA_CN) REFERENCES dbo.CHI_NHANH (MA_CN)
ALTER TABLE dbo.SAN_PHAM ADD FOREIGN KEY (MA_HH) REFERENCES dbo.HANG_HOA (MA_HH)
ALTER TABLE dbo.TRANG_THAI ADD FOREIGN KEY (MA_DH) REFERENCES dbo.DON_HANG (MA_DH)
ALTER TABLE dbo.CHI_TIET_DH ADD FOREIGN KEY (MA_DH) REFERENCES dbo.DON_HANG (MA_DH)
ALTER TABLE dbo.CHI_TIET_DH ADD FOREIGN KEY (MA_SP) REFERENCES dbo.SAN_PHAM (MA_SP) -- lỗi
ALTER TABLE dbo.KHACH_HANG ADD FOREIGN KEY (MA_TK) REFERENCES dbo.TAI_KHOAN (MA_TK)
ALTER TABLE dbo.TAI_XE ADD FOREIGN KEY (MA_TK) REFERENCES dbo.TAI_KHOAN (MA_TK)
ALTER TABLE dbo.TAI_XE ADD FOREIGN KEY (MA_KV) REFERENCES dbo.KHU_VUC_HOAT_DONG (MA_KV)